.TH VIMCAT 1
.SH NAME
vimcat \- Concatenate files with vim-provided syntax highlighting
.SH SYNOPSIS
.B \fBvimcat\fR [\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
\fBvimcat\fR works like \fBcat\fR but uses ANSI terminal escape sequences to
syntax-highlight printed text as \fBvim\fR would.
.PP
All your typical \fBvim\fR configuration is applied by \fBvimcat\fR. That is,
your vimrc, ftdetect rules, after/syntax tweaks, ... \fBvimcat\fR quite
literally runs \fBvim\fR to display the given files and then renders the result
in your terminal.
.SH OPTIONS
\fB-c\fR \fIwhen\fR, \fB--color=\fR\fIwhen\fR, \fB--color=\fR\fIwhen\fR
.RS
Control whether output is printed with syntax highlighting or without. Possible
values of \fIwhen\fR are \fBalways\fR, \fBauto\fR, and \fBnever\fR. When
\fBauto\fR is used (the default), the \fBNO_COLOR\fR environment variable will
also be checked to see if colour should be disabled. In contrast to many other
tools, \fBvimcat\fR does not consider whether stdout is a TTY but rather assumes
colour is generally desired.
.RE
.PP
\fB-d\fR, \fB--debug\fR
.RS
Enable debugging output. This is generally only useful when debugging
\fBvimcat\fR itself. However you may find some of your vimrc settings cause an
unintended effect or deadlock, in which case this flag may help you discover
which configuration line is to blame.
.RE
.PP
\fB-v\fR, \fB--version\fR
.RS
Output version information and exit. Note that the version information is the
version of the underlying libvimcat that \fBvimcat\fR is linked to.
.RE
.SH AUTHOR
All comments, questions and complaints should be directed to Matthew Fernandez
<matthew.fernandez@gmail.com>.
.SH LICENSE
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
