task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:

    - name: FreeBSD
      freebsd_instance:
        image_family: freebsd-15-0-snap
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: pkg upgrade -y && pkg install -y cmake py39-pytest vim
      test_script: uname -sr && env && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- check && cmake --build . -- install

    - name: Linux
      container:
        image: gcc:13.2
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        LC_ALL: C.UTF-8
        PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update && apt-get install --no-install-recommends -y python3-pytest vim xxd && wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf cmake-3.21.1-linux-x86_64.tar.gz --directory /opt
      test_script: uname -sr && env && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- check && cmake --build . -- install

    - name: Linux, release build
      container:
        image: gcc:13.2
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        LC_ALL: C.UTF-8
        PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update && apt-get install --no-install-recommends -y python3-pytest vim xxd && wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf cmake-3.21.1-linux-x86_64.tar.gz --directory /opt
      test_script: uname -sr && env && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && cmake --build . -- check && cmake --build . -- install

    - name: macOS
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: pip3 install pytest
      test_script: uname -sr && env && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- check && sudo cmake --build . -- install

    - name: clang-format
      container:
        image: silkeh/clang:15
      install_script: apt-get update && apt-get install --no-install-recommends -y git
      test_script: git ls-files -z '**/*.c' '**/*.h' | xargs -0 -- clang-format --dry-run --style=file --Werror
