name: Github Actions CI
permissions: {}
on:
  pull_request:
    branches:
      - main
jobs:
  freebsd13:
    name: FreeBSD
    runs-on: ubuntu-24.04
    steps:
    - uses: vmactions/freebsd-vm@7ca82f79fe3078fecded6d3a2bff094995447bbd
      with:
        sync: no
        release: "15.0"
        usesh: true
        run: |
          set -e
          set -o pipefail
          set -u
          set -x
          uname -rms
          pkg install -y cmake git python3 py311-pytest vim
          python3 --version
          git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
          cd wd
          git fetch -- origin ${{ github.event.pull_request.head.sha }}
          git checkout FETCH_HEAD
          export CFLAGS="-Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined"
          export UBSAN_OPTIONS=print_stacktrace=1
          export TERM=xterm
          cmake -B build -S .
          cmake --build build
          cmake --build build --target check
          cmake --install build

  linux:
    name: Linux
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y python3-pytest vim xxd
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: cmake --build build --target check
      - run: sudo cmake --install build

  linux_shared:
    name: Linux, shared libraries
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y python3-pytest vim xxd
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -DBUILD_SHARED_LIBS=ON -B build -S wd
      - run: cmake --build build
      - run: cmake --build build --target check
      - run: sudo cmake --install build

  linux_release:
    name: Linux, release build
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y python3-pytest vim xxd
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -DCMAKE_BUILD_TYPE=Release -B build -S wd
      - run: cmake --build build
      - run: cmake --build build --target check
      - run: sudo cmake --install build

  macos:
    name: macOS
    runs-on: macos-26-intel
    env:
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: env PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cmake -B build -S wd
      - run: cmake --build build
      - run: cmake --build build --target check
      - run: sudo cmake --install build

  c_format:
    name: C format
    runs-on: ubuntu-22.04
    steps:
      - run: uname -rms
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cd wd && git ls-files -z '**/*.c' '**/*.h' | xargs -0 -- clang-format-15 --dry-run --style=file --Werror

  py_format:
    name: Python format
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: uname -rms
      - run: python3 --version
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y black python3-isort python3-pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: cd wd && git fetch -- origin ${{ github.event.pull_request.head.sha }} && git checkout FETCH_HEAD
      - run: cd wd && git ls-files -z '**/*.py' | xargs -0 -- python3 -m black --check --
      - run: cd wd && git ls-files -z '**/*.py' | xargs -0 -- python3 -m isort --profile=black --check --
      - run: python3 -m pip install --user pylint
      - run: cd wd && git ls-files -z '**/*.py' | xargs -0 -- python3 -m pylint --
